---
title: "Generating Figure S3 - RPKM varies across TVV species"
author: "Austin Reid Manny"
date: "2021-04-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(ggpubr)
```

```{r read data}
table_s1 <- read_csv(file = "table-s1-summarized.csv") %>% drop_na()
```

```{r plot data}
fig_s3 <- ggplot(data = table_s1,
                        mapping = aes(x = Species,
                                      y = RPKM)) +
                 geom_boxplot() + 
                 theme_bw() +
                 ggtitle("RPKM values per TVV species") +
                 scale_y_log10() +
                 theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
                 stat_compare_means(label.x = 4.47, label.y = 2.1)

fig_s3
```

```{r save the plot}
# Save it
ggsave(
  "FigS3 RPKM-values-by-TVV.jpeg",
  plot = fig_s3,
  device = "jpeg",
  scale = 1,
  width = 8.5,
  height = 6.8,
  units = "in",
  dpi = 300
  )
```

